#!/bin/bash

# Find an on disk executable alternative

source bash-helpers

app=${1?Specify app}

if ! [[ $app =~ / ]] ; then
    DIE "Specify absolute path to executable."
fi

if ! [ -x $app ] ; then
    DIE "Specify existing executable."
fi

base=$(basename $app)

INFO "Searching for alternative for $base ($app)"

while read candidate ; do

    if [[ $candidate = $app ]] ; then
        continue
    fi

    if [[ $candidate = $REMOTE_HOME/.bin/$base ]] ; then
        continue
    fi

    INFO "Found alternative $candidate"

    RETURN $candidate

done <<EOF
    $(type -ap $base || echo $app)
EOF

DIE "No alternative found for $base ($app)"
