#!/bin/bash

# Find an on disk executable alternative and run it

set -e

source bash-helpers

app=$1 ; shift

if [[ $SHLVL -gt 20 ]] ; then
    DIE "Recursion depth of $SHLVL detected."
fi

alternative=$(alternative $app)

exec $alternative "$@"
