#!/bin/bash

# Install packages listed in a file

source bash-helpers

INFO "FYI - this will install outstanding upgrades too."

file=${1?file name?}
perl -pe 's/^(.+)$/$1 install/g' $file | dpkg --set-selections
apt-get dselect-upgrade
