#!/bin/bash

# Copy a file to ~/backups/ appending a timestamp

set -e

source bash-helpers

file=${1?filename not specified}
file=$(perl -pe 's/\/$//g' <<<"$file")
bak=$(basename "$file")
bak=$REMOTE_HOME/backup/"$bak""_"$(date +%Y%m%d_%H%M%S)

INFO "Copying: $file -> $bak"

cp -a "$file" "$bak"
