#!/bin/bash

# Archive a file appending a timestamp

set -e

source bash-helpers

file=${1?filename not specified}
file=$(perl -pe 's/\/$//g' <<<"$file")
bak=$(basename "$file")
bak=$REMOTE_HOME/backup/"$bak""_"$(date +%Y%m%d_%H%M%S)

INFO "Archiving to: $file -> $bak"

mv "$file" "$bak"
