#!/usr/bin/env node
// Add a leading two digit track number to the file name

var fs = require('fs')
var mm = require('musicmetadata')
var sprintf = require('sprint')
var src = process.argv[2]

var parser = mm(fs.createReadStream(src), function (err, metadata) {
    if (err) throw err
    if(!metadata.track.no) {
      throw new Error("No track number found")
    }
    var dst = sprintf("%.2d", metadata.track.no) + "_" + src
    console.log("mv " + src + " -> " + dst)
    fs.renameSync(src, dst)
  }
)

