#!/bin/bash

# Backup a file appending a timestamp

source bash-helpers

file=${1?filename not specified}
info=$2

if [[ $info ]] ; then
    info=".$info"
fi

# remove optional trailing slash
file=${file%/}
bak=$file"_"$(date +%Y%m%d_%H%M%S)$info

INFO "Backing up: $file -> $bak"

if [ -d $file ] ; then
    cp -a $file $bak
else
    cp $file $bak
fi
