#!/bin/bash

# Backup a file appending a timestamp

source bash-helpers

file=${1?filename not specified}

# remove optional trailing slash
file=${file%/}
bak=$file"_"$(date +%Y%m%d_%H%M%S)

INFO "Backing up: $file -> $bak"

if [ -d $file ] ; then
    cp -r $file $bak
else
    cp $file $bak
fi
