#!/bin/bash


# Add an entry to the eternal history

source bash-helpers

cmd="$@"

test -z $HISTFILE_ETERNAL && DIE "Set env var: HISTFILE_ETERNAL"
test -z "$cmd" && DIE "Specify command"

test -z $PRIVATE_SHELL || exit 0

if [[ $cmd == "rm "* ]] ; then
    cmd="# $cmd"
fi

quoted_pwd=${PWD//\"/\\\"}

# update cleanup_eternal_history if changed:
# use LOGNAME when coming from CGI
line="$USER""$LOGNAME"
line="$line $(date +'%F %T')"
line="$line $BASHPID"
line="$line \"$quoted_pwd\""
line="$line \"0\""
line="$line $cmd"
echo "$line" >> $HISTFILE_ETERNAL

