#!/usr/bin/env perl

# Unpack fatpacked apps to $REMOTE_HOME/.bin

use strict;
use warnings;

$/ = undef;
open( my $f, $ENV{REMOTE_BASHRC} ) || die $!;
my $bashrc = <$f>;

my $home = $ENV{REMOTE_HOME} || die "REMOTE_HOME not set";
my $dst_dir = $ENV{REMOTE_HOME} . "/.bin";

system("mkdir -p $dst_dir") && die $!;

while ( $bashrc =~ /^### fatpacked app ([\w-]+) #*\n\n(.*?)### /igsm ) {

    my $app_name = $1;
    my $app_data = $2;

    my $app_file_name = "$dst_dir/$app_name";

    print STDERR "Exporting $app_name to $app_file_name...\n";

    open (my $APP_FILE, ">", $app_file_name) || die $!;
    print $APP_FILE $app_data;
    print $APP_FILE "\n# This app was created automatically an may be overridden - DONT TOUCH THIS.";
}
