#!/bin/bash

# Helper functions for shell scripts
# Put in you path and you can use them using "source bash-helpers".

set -e
set -o pipefail

if [[ $BASHRC_PROMPT_COLORS ]] ; then
    NO_COLOR='\[\e[33;0;m\]'
        GRAY='\[\e[38;5;243m\]'
        GREY='\[\e[38;5;243m\]'
       GREEN='\[\e[38;5;2m\]'
      ORANGE='\[\e[38;5;3m\]'
         RED='\[\e[38;5;9m\]'
else
    NO_COLOR=$(echo -e '\x1b[33;0;m')
        GRAY=$(echo -e '\x1b[38;5;243m')
        GREY=$(echo -e '\x1b[38;5;243m')
       GREEN=$(echo -e '\x1b[38;5;2m')
      ORANGE=$(echo -e '\x1b[38;5;')
         RED=$(echo -e '\x1b[38;5;9m')
fi

function _LOG() {

    local level=$1 ; shift

    local log_level_prio
    local crap
    read log_level_prio crap <<<$(_calc_prio $LOG_LEVEL)

    if [[ ! $LOG_LEVEL ]] ; then
        if [[ -t 1 ]] ; then
            log_level_prio=3
        else
            log_level_prio=6
        fi
    fi

    local location

    local prio
    local show_location
    local color

    read prio show_location color <<<$(_calc_prio $level)

    if [[ $prio < $log_level_prio ]] ; then
        return
    fi

    if [[ $show_location > 0 ]] ; then

        local function
        local file

        read location function file <<<$(caller 1)

        if [[ $file ]] ; then
            location=$(basename $file)":"$location
        fi

        if [[ $location ]] ; then
            location=" "$location
        fi
    fi

    if [ -t 1 ] ; then
        echo -e "$color${level}$location> $@${NO_COLOR}" >&2
    else
        echo -e "$(date +'%F %T') ${level}$location> $@" >&2
    fi
}

function _calc_prio() {

    local level=$1

    local prio
    local show_location
    local color

    case $level in
        TRACE) prio=1 ; show_location=1 ; color=$GRAY ;;
        DEBUG) prio=2 ; show_location=0 ; color=$GRAY ;;
        INFO)  prio=3 ; show_location=0 ; color=$GREEN ;;
        WARN)  prio=4 ; show_location=0 ; color=$ORANGE ;;
        ERROR) prio=5 ; show_location=1 ; color=$RED ;;
        FATAL) prio=6 ; show_location=1 ; color=$RED ;;
    esac

    echo $prio $show_location $color
}

function TRACE()  { _LOG "TRACE" "$@" ; }
function DEBUG()  { _LOG "DEBUG" "$@" ; }
function INFO()   { _LOG "INFO " "$@" ; }
function WARN()   { _LOG "WARN " "$@" ; }
function ERROR()  { _LOG "ERROR" "$@" ; }
function DIE()    { _LOG "FATAL" "$@" ; exit 1 ; }
function RETURN() { echo -ne "$@"     ; exit 0 ; }

function EXIT()   {
    if [[ "$@" ]] ; then
        _LOG "INFO"  "$@"
    fi
    exit 0
}

function usefatal() {
    trap DIE ERR
}

function nousefatal() {
    trap ERR
}

function repeat() {
    perl -0777 -e 'print <STDIN> x $ARGV[0]' "$@"
}

# Print a line with a message the length of the screen.
function line() {
    perl - $@ <<'EOF'
        my $msg = " " . join(" ", @ARGV) . " ";
        print "---", $msg , q{-} x ($ENV{COLUMNS} - 3 - length($msg)), "\n\n";
EOF
}

function prefixif() {
    
    if [[ "$@" ]] ; then
        echo -ne " $@"
        return
    fi

    echo -ne "$@"
}

function docopt() {
    docopt='docopt-convert $(readlink -f $0) -- "$@"'
    eval $docopt
    docopt=$(eval $docopt)
}
