#!/bin/bash

# Generate and deploy fat packed bashrc

set -e

cd ~/src/dotfiles
git pull || echo "Nothing to pull"

cd ~/src/bashrc
git reset --hard HEAD
git pull || echo "Nothing to pull"

cd ~/src/bin
./bashrc-pack

cd ~/src/bashrc
git add bashrc
git commit -m "repackage bashrc"
git push
