#!/usr/bin/env bash

# Install and run specified installer_command

# Can not be run from within ~/.bin...

source bash-helpers

app=${1?Specify app}
shift
nothing=${1?Specify installer_command}
installer_command="$@"

if [[ $app =~ / ]] ; then
  app=$(basename $app)
fi

abs_app="$REMOTE_HOME/.bin/$app"

set +e
already_exists=$(type -a $app 2>/dev/null | grep -v $abs_app)
set -e

if [[ "$already_exists" = "" ]] ; then
  INFO "Installing $app via '$installer_command'..."
  $installer_command
fi

exec alternative-run $abs_app
