#!/usr/bin/env perl

# Attach scripts to the bashrc skeleton

use strict;
use warnings;
use Path::Tiny;

die "Not in bin dir." if path(".")->absolute->basename ne "bin";

my $bashrc_skel = path("../dotfiles/bashrc");
my $bashrc_phat = path("../bashrc/bashrc");

$bashrc_skel->copy($bashrc_phat);

my $apps_count = 0;

foreach my $bin (sort (path(".")->children)) {

    next if $bin->is_dir;

    # say STDERR "Packing $bin...";

    my $description = "fatpacked app $bin";

    $bashrc_phat->append("### ", $description, " ",
        "#" x (80 - length($description) - 5) . "\n\n");

    $bashrc_phat->append($bin->slurp, "\n");

    $apps_count++;
}

$bashrc_phat->append("### fatpacked apps END", "#" x 57, "\n");

print "Done - apps packed: $apps_count\n";
