#!/usr/bin/env bash

# Environment fixes to run on specific linux distributions

source bash-helpers

[[ $DISTRIB_ID = "" ]] && exit

fix_file=bashrc-linux-distribution-fix-$DISTRIB_ID
if [[ $(type -t $fix_file) ]] ; then
    . $fix_file
fi
