#!/usr/bin/env node

// Attach scripts to the bashrc skeleton

const LogDwim = require(`log-dwim`)
const logger = new LogDwim()
const { TRACE, DEBUG, INFO, WARN, ERROR, DIE, DUMP } = logger

const path = require(`path`)
const fs = require(`fs-extra`)
const glob = require(`glob`).sync
const _ = require(`lodash`)

const wd = path.join(process.env.HOME, `src`, `bin`)
process.chdir(wd)

let bashrc = fs.readFileSync("../dotfiles/bashrc").toString()
let bashrcFileName = path.resolve("../bashrc/bashrc")

let appsCount = 0

let filesToSkip = [
  `README`,
  `package-lock.json`,
]

INFO(`Packing bin...`)
for (const binFileName of glob(path.join(wd, '*'))) {
  if(fs.lstatSync(binFileName).isDirectory()) {
    continue
  }
  if(filesToSkip.includes(path.basename(binFileName))) {
    continue
  }

  DEBUG(`binFileName:`, binFileName)
  const bin = fs.readFileSync(binFileName).toString()
  let description = `fatpacked app ${path.basename(binFileName)}`
  bashrc += _.padEnd("### " + description + " ", 80, `#`) + "\n\n"
  bashrc += bin + "\n"
  appsCount++;
}

bashrc += _.padEnd("### fatpacked apps END ", 80, "#") + "\n\n"
fs.writeFileSync(bashrcFileName, bashrc)

INFO(`Done - apps packed: ${appsCount}`)
