#!/usr/bin/env bash

# Remove comments from a bash script and run it

# This allows comments like this:
# app \
#   # description of option
#   -w   \
#   -x   \ # description of option
#   # -y \ # deactivated option
#   -z

script=$1
shift

tmp=$(tempfile)

perl -007pe 's/^\s*#.*\n//gm ; s/^\s*#.*\s+//gm' < $script > $tmp
chmod +x $tmp
exec -a "$script" $tmp "$@"

