#!/usr/bin/env perl

# Allow cpanm to install modules specified via Path/File.pm

map { s/\//\:\:/g ; s/\.pm$//g } $ARGV[$#ARGV];

my @local_lib = ( "--local-lib", "$ENV{REMOTE_HOME}/perl5" );

system("alternative-run", "$0", "-nq", @local_lib , @ARGV) && exit 1;
