#!/usr/bin/env perl

# Allow cpanm to install modules specified via Path/File.pm

map { s/\//\:\:/g ; s/\.pm$//g } @ARGV;

system("alternative-run", "$0", "-nq --local-lib $REMOTE_HOME/perl5" , @ARGV) && exit 1;
