#!/bin/bash

# Create tags for all source directories

set -e

ctags-setup

# Save absolute path in tags file
cd /

ctags -f ~/.vim/var/tags -R ~/src
# $(perl -e 'print join(" ",  grep(!/^\./, @INC))')
