#!/usr/bin/env perl

# Generate README with descriptions for bin scripts

use strict;
use warnings;
no warnings 'uninitialized';
use Path::Tiny;
use Text::Wrap;
$Text::Wrap::columns = 72;

die "Current dir not called bin" if !path(".")->basename eq "bin";

my $readme = path("README");
my ($preamble) = $readme->slurp =~ /(.+Descriptions\:)/igms;

$readme->spew("$preamble\n\n");

foreach my $app (sort(path(".")->children)) {

    next if $app->is_dir;
    next if $app->basename =~ /^\.|^readme$|^package.*json$|^authorized_keys$/i;

    my ($description) = $app->slurp =~ /^=head1 NAME\s+(.+)/m;
    ($description) = $app->slurp =~ /^# (.+?)\n/m if !$description;
    ($description) = $app->slurp =~ /^\/\/ (.+?)\n/m if !$description;

    $description =~ s/^$app[\s-]*//g;

    $description = wrap('    ', '    ', $description) if $description;

    print STDERR "Description ends with a dot app: $app\n"
        if $description =~ /\.$/;

    print STDERR "No description found for app: $app\n" if !$description;
    $description ||= "    TODO";

    $readme->append("$app:\n$description\n");
}
