#!/bin/bash

# Cleaned up df version

source bash-helpers

if [[ $@ ]] ; then
    alternative-run $0 "$@"
    EXIT
fi

alternative-run $0 -h \
    | perl -0777 -pe 's/Mounted on/Mounted_on/gm' \
    | perl -0777 -pe 's/^(\S+)\n/$1/gm' \
    | csvview \
    | less -S
