#!/usr/bin/env bash

# Diff 2 directories recursively comparing file contents and not file attributes
# (timestamp etc)

source bash-helpers

src=${1:?Specify src}
dst=${2:-.}

rsync -nrclD --delete --exclude /.git --info COPY,DEL,NAME,SYMSAFE $src/ $dst/
