#!/bin/bash 

# Find files excluding dotfiles optionally matching several strings

source bash-helpers

head_warn="head-warn"

path=$(abs .)

if [[ $1 = '--dir' ]] ; then
    shift
    path=$1
    shift
fi

if [[ $1 = '--project' ]] ; then
    shift

    set +e
    git_root=$(git-root)
    set -e

    if [[ $git_root ]] ; then
        path=$git_root
    fi
fi

if [[ $1 = '--no-limit' ]] ; then
    shift
    head_warn=cat
fi

cd /

set +e

find \
    -H \
    $path \
    -mount \
    -type f \
    | perl -ne 'print if ! m#'$path'\..*#' \
    | perl -ne 'print if ! m#'$path'(node_modules|bower_components|classes|coverage)/.*#' \
    | grep-and -i "$path" -e $@ \
    | head -101 \
    | sort-by-path-depth \
    | $head_warn

exit 0
