#!/bin/bash 

# Find files excluding dotfiles optional matching several strings

source bash-helpers

if [[ $1 = '--fallback-to-cwd' ]] ; then
    shift
    fallback=1
fi

if [[ $1 = '--dir' ]] ; then
    shift
    cd $1
    shift
fi

if [[ $1 = '--project' ]] ; then
    shift

    set +e
    gitroot=$(git-root)
    set -e

    if [[ $gitroot ]] ; then
        cd $gitroot
    else
      if [[ ! $fallback ]] ; then
        DIE No project root found
      fi
    fi
fi

if [[ $1 = '--abs' ]] ; then
    shift
    abs=1
fi

if [[ $abs ]] ; then
    export abs=$(abs)
fi


find -H * -mount \
    -type f \
    | perl -ne 'print if ! m#/\.#' \
    | perl -pe 's#^#$ENV{abs}# if $ENV{abs}' \
    | perl -ne 'print if ! m#(^|/)node_modules/#' \
    | perl -ne 'print if ! m#(^|/)bower_components/#' \
    | perl -ne 'print if ! m#(^|/)classes/#' \
    | grep-and -e $@


