#!/bin/bash

# Default options for git commands

source bash-helpers

if [[ $1 == "status" ]] ; then

    shift
    alternative-run $0 status -uall "${@:2}" "$@"

elif [[ $1 == "log" ]] ; then

    shift
    alternative-run $0 log --decorate --graph --format='%h: %s | %ar by %an' "$@"

else
    alternative-run $0 "$@"
fi
