#!/bin/bash

# Default options for git commands

source bash-helpers

if [[ $1 == "status" ]] ; then

    shift
    alternative-run $0 status -uall "${@:2}" "$@"

elif [[ $1 == "log" ]] ; then

    shift

    files="$@"

    if [[ ! "$files" ]] ; then
        files="."
    fi

    alternative-run $0 log --follow --decorate --graph --format='%h: %s | %ar by %an' "$files"

else
    alternative-run $0 "$@"
fi

