#!/bin/bash

# Ensure git-scm is configured appropriately

set -e

source bash-helpers

git config --global --get user.name  > /dev/null && DIE 'Global user name set!'
git config --global --get user.email > /dev/null && DIE 'Global user email set!'

exit 0
