#!/bin/bash

# Discard commits dating back to specified commit

set -e

source bash-helpers

commit_id=${1?Specify commit id}

git reset --hard $commit_id

INFO "Push now with: git push origin HEAD --force"
