#!/usr/bin/env perl

# Search for lines matching one or more perl regex patterns

use strict;
use warnings;
use Data::Dumper;

use Getopt::Long;
Getopt::Long::Configure("bundling");

my $red      = "\x1b[38;5;124m";
my $no_color = "\x1b[33;0m";

if (!-t STDOUT) {
    $red = $no_color = "";
}

my $opts = {
    "f|file=s"           => \my $file,
    "p|prefix-file-name" => \my $prefix,
    "e|allow-empty"      => \my $allow_empty,
};
GetOptions(%$opts) or die "Usage:\n$0 " . join("\n", sort keys %$opts) . "\n";

my @patterns = @ARGV;

if (!$allow_empty) {
    @patterns || die "Specify patterns to search for.";
}

my $h = *STDIN;
if ($file) {
    open($h, $file) || die $!;
}

LINE: while (<$h>) {

    if (!@patterns && $allow_empty) {
        print;
        next;
    }

    foreach my $pattern (@patterns) {
        if (!s/(\Q$pattern\E)/$red$1$no_color/gi) {
            next LINE;
        }
    }

    if ($prefix) {
        printf("%s:%5s: %s", $file, $., $_);
    }
    else {
        print;
    }
}
