#!/usr/bin/perl
# Limit input lines and warn if more lines are left

use strict;
use warnings;
no warnings 'uninitialized';

my $count = 0;
my $limit = 100;

if($ARGV[0] =~ /-(\d+)/) {
  $limit = $1;
}

my $red      = "\x1b[38;5;124m";
my $no_color = "\x1b[33;0m";

if (!-t STDOUT) {
    $red = $no_color = "";
}

my $last;
while(<STDIN>) {
  $count++;

  if($count == $limit + 1) {
    print $last;
    print STDERR $red . "### Limit of $limit exceeded. ###" . $no_color . "\n";
    exit 0;
  }

  print $last if $last;

  $last = $_;
}

print $last;
