#!/bin/bash

# Forward an incoming port to a different port
# Often needed to map a privileged port to an unprivileged one.

source bash-helpers

src=${1?Specify incoming port}
dst=${2?Specify outgoing port}

sudo iptables -t nat -A PREROUTING -p tcp --dport $src -j REDIRECT --to-port $dst
