#!/usr/bin/env bash

# Turn keyboard backlight off permanently

source bash-helpers

gotroot

sudo apt install sysfsutils

cat << EOF >> /etc/sysfs.conf
devices/platform/dell-laptop/leds/dell\:\:kbd_backlight/brightness = 0
EOF

