#!/usr/bin/env bash

# Setup local mail delivery on ubuntu 18.04

source bash-helpers

gotroot

forwardRootTo=${1:?Specify username to forward root mail to.}

apt-get install postfix mailutils mutt

bak /etc/aliases

cat << EOF > /etc/aliases
# See man 5 aliases for format
postmaster:    root
root: $forwardRootTo@localhost
EOF

newaliases
service postfix restart

if [[ -e /root/.forward ]] ; then
  bakmp /root/.forward
fi

if [[ -e /home/$forwardRootTo/.forward ]] ; then
  bakmp /home/$forwardRootTo/.forward
fi
