#!/bin/bash

# Lookup help for a command in several places

source bash-helpers

set +e

COLUMNS=80

# format output in pipes too
MAN_KEEP_FORMATTING=1 

function _printifok() {
    local msg=$1 ; shift
    local quote=$1 ; shift
    local cmd="$*"

    local out=$($cmd 2>/dev/null)
    [[ ${out[@]} ]] || return 1
    line $msg
    if [[ $quote = 1 ]] ; then
        echo "${out[@]}" | perl -pe 's/^/#   /g'
    else
        echo "${out[@]}"
    fi
    echo
}

cmd=$1 ; shift

if [[ $cmd = git ]] ; then
    cmd=$cmd-$1
    shift
fi

arg="$1"

if [[ $arg =~ ^-- ]] ; then
   arg="+/$arg"
elif [[ $arg =~ ^- ]] ; then
   arg="+/^\\s+$arg"
elif [[ $arg ]] ; then
   arg="+/$arg"
else
   arg='+/^--- .+ -+$'
fi

(
    _printifok options 0 man-explain-options $cmd "$@"
    _printifok help 0 help -m $cmd
    _printifok man 0 man -a $cmd
    _printifok perldoc 0 perldoc -f $cmd
    _printifok npm-readme 0 npm-readme $cmd

    if [[ ! $SHORT ]] ; then
        _printifok related 1 man -k $cmd
        _printifok "apt show" 1 apt-cache show $cmd
        _printifok "apt search" 1 apt-cache search $cmd
    fi

) | LESS="-inRgSj.5" less "$arg"

