#!/bin/bash

# Lookup help for a command in several places

source bash-helpers

set +e

COLUMNS=80

# format output in pipes too
MAN_KEEP_FORMATTING=1 

function _printifok() {
    local msg=$1 ; shift
    local cmd="$*"

    local out=$($cmd 2>/dev/null)
    [[ ${out[@]} ]] || return 1
    line $msg
    echo "${out[@]}"
    echo
}

cmd=$1 ; shift

if [[ $cmd = git ]] ; then
    cmd=$cmd-$1
    shift
fi

arg="$1"

if [[ $arg =~ ^-- ]] ; then
   arg="+/$arg"
elif [[ $arg =~ ^- ]] ; then
   arg="+/^\\s+$arg"
elif [[ $arg ]] ; then
   arg="+/$arg"
else
   arg='+/^--- .+ -+$'
fi

(
    _printifok options man-explain-options $cmd "$@"
    _printifok help help -m $cmd
    _printifok man man -a $cmd
    _printifok perldoc perldoc -f $cmd
    _printifok related man -k $cmd
    _printifok "apt show" apt-cache show $cmd
    _printifok "apt search" apt-cache search $cmd

) | LESS="-inRg" less "$arg"
