#!/bin/bash

# Lookup help for a command in several places

source bash-helpers

set +e

COLUMNS=80

# format output in pipes too
MAN_KEEP_FORMATTING=1 

function _printifok() {
  local msg=$1 ; shift
  local cmd="$*"

  local out=$($cmd 2>/dev/null)
  if [[ -z $out ]] ; then
    return 1
  fi
  line $msg
  echo "${out[@]}"
  echo
}

function _printifany() {
  local msg=$1 ; shift
  local cmd="$*"
  # type $cmd &>/dev/null || return

  local out=$($cmd 2>&1)
  # perldoc
  if [[ -z $out ]] ; then
    return
  fi

  line $msg
  echo "${out[@]}"
  echo
}

cmd=$1 ; shift
arg="$1"

if [[ $arg =~ ^-- ]] ; then
   arg="+/$arg"
elif [[ $arg =~ ^- ]] ; then
   arg="+/^\\s+$arg"
elif [[ $arg ]] ; then
   arg="+/$arg"
else
   # arg='+/^--- .+ -+$'
   arg='+/^\w+\([0-9]\).+|^--- .+ -+$'
fi

(
_printifok options man-explain-options $cmd "$@"
_printifok help help -m $cmd
_printifok man man -a $cmd
_printifok README npm-readme $cmd
_printifok perldoc perldoc -f $cmd

if [[ $RUN_HELP ]] ; then
  _printifany "--help" $cmd --help
fi

if [[ $ALL ]] ; then
  _printifok related man -k $cmd
  _printifok "apt show" apt-cache show $cmd
  _printifok "apt search" apt-cache search $cmd
fi
) | LESS="-inRgSj.5" less "$arg"
