#!/usr/bin/env bash

# create a backup

source bash-helpers

mount_dirs=/media/$USER/*backup*

set +e
mounts=$(ls -d $mount_dirs 2>/dev/null | wc -l) 
set -e

if [[ $mounts == 0 ]] ; then
  DIE "No backup drive found - please connect drive."
fi

if [[ $mounts > 1 ]] ; then
  DIE "Too many backup drives found - please disconnect all but one."
fi

drive=$(ls -d $mount_dirs)

src=${1:?Specify directory to backup}
basename=$(basename "$src")

dst=$drive/${basename}_backup
dst_current=$dst/current

timestamp=$(date +%Y%m%d_%H%M%S)
history=../history/${basename}_${timestamp}

INFO "Backing up to: $dst"

app_id="5774adbf-d22e-48dc-b0ed-6fb0a8abc901"
id_file=$dst/.$app_id

if [[ -d "$dst" ]] ; then
  if [[ ! -e "$id_file" ]] ; then
    DIE "Directory already extists: $dst"
  fi
fi

mkdir -p $dst_current
touch $id_file

set -x
rsync \
  -a \
  --delete \
  --delete-excluded \
  -b --backup-dir $history \
  --exclude /.cache \
  --exclude /.thumbnails \
  --exclude /.Trash \
  --exclude /.local/share/Trash \
  --exclude /.Xauthority \
  --exclude /tmp \
  $src/ $dst_current/

INFO "Backup done."

