#!/bin/bash

# Fix mysql prompt to show real hostname - NEVER localhost.

h=$(perl -e '"'"$*"'" =~ /[-]+h(?:ost)*\ ([^ \\.]+)/ && print $1')

if [[ ! $h || $h = localhost ]] ; then
    h=$HOSTNAME
fi

if [[ $(type -t luit) ]] ; then
    luit="luit -encoding ISO885915"
fi

# MYSQL_PS1="\\u@${GREEN}$h${NO_COLOR}:${RED}\\d db${NO_COLOR}> " \
xtitle "mysql@$h" && \
    MYSQL_PS1="\\u@$h:\\d db> " \
    command $luit mysql --default-character-set=latin1 \
        --show-warnings --pager="less -FX" "$@"
