#!/usr/bin/env bash

# Setup neovim

source bash-helpers

sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neovim

sudo apt-get install python-dev python-pip python3-dev python3-pip

pip3 install --user neovim
