#!/bin/bash

# Install latest node version

source bash-helpers

node_dst=~/opt/node
node_bin=~/opt/bin/node
npm_bin=~/opt/bin/npm
backup=~/opt/node-install.backup.$(date +%Y%m%d_%H%M%S)

if [[ -e $node_dst || -h $node_dst || -e $node_bin || -h $node_bin || -e $npm_bin || -h $npm_bin ]] ; then

    if [[ $1 != "--force" ]] ; then
        DIE "Found existing node in ~/opt - use --force if you are sure"
    fi

    INFO "Backing up existing node to $backup"
    mkdir -p $backup
fi

wd=$(mktemp -d --suffix=.node-install)
cd $wd

bits=$(uname -m | perl -ne 'print $1 if /_(32|64)$/')

url=https://nodejs.org/dist/latest

file=$(wget -q -O - $url | perl -ne 'print $1 if /(node-v[\d\.]+-linux-x'$bits'.tar.gz)/i')
url=$url/$file
dir=$(echo $file | perl -pe 's/\.tar.gz//g')

INFO "Downloading: $url"
wget -q $url

INFO "Extracting to $dir"
tar xfz $file

rm $file

mkdir -p ~/opt/bin

node_dst_versioned=~/opt/$dir

for file in $node_dst $node_dst_versioned $node_bin $npm_bin ; do
    if [ -e $file ] || [ -d $file ] || [ -L $file ] ; then
        INFO "Backing up $file to $backup/..."
        mv $file $backup/
    fi
done

mv $dir $node_dst_versioned

cd ~/opt
ln -s $dir node

cd ~/opt/bin
ln -s ../node/bin/node .

PATH=$PATH:~/opt/$dir/bin
npm-set-global-modules-dir
npm-set-proxy-from-environment

INFO "Installing newest npm via npm"
npm install -g npm@latest >/dev/null

INFO "Done."


