#!/bin/bash

# Install latest node version

source bash-helpers

node_dst=~/opt/node
node_bin=~/opt/bin/node
npm_bin=~/opt/bin/npm
backup=$node_dst.backup.$(date +%Y%m%d_%H%M%S)

if [[ -e $node_dst || -h $node_dst || -e $node_bin || -h $node_bin || -e $npm_bin || -h $npm_bin ]] ; then

    if [[ $1 != "--force" ]] ; then
        DIE "Found existing node in ~/opt - use --force if you are sure"
    fi

    INFO "Backing up existing node to $backup"
    mkdir -p $backup
fi


wd=$(mktemp -d)
cd $wd

bits=$(uname -m | perl -ne 'print $1 if /_(32|64)$/')

url=https://nodejs.org/dist/latest

file=$(wget -q -O - $url | perl -ne 'print $1 if /(node-v[\d\.]+-linux-x'$bits'.tar.gz)/i')
url=$url/$file
dir=$(echo $file | perl -pe 's/\.tar.gz//g')

INFO "Downloading: $url"
wget -q $url

INFO "Extracting to $dir"
tar xfz $file

rm $file

mkdir -p ~/opt/bin

node_dst_versioned=~/opt/$dir

mv $node_dst $backup/ || true
mv $node_dst_versioned $backup/ || true
mv $node_bin $backup/ || true
mv $npm_bin $backup/ || true

mv $dir $node_dst_versioned

cd ~/opt
ln -s $dir node

cd ~/opt/bin
ln -s ../node/bin/node .
ln -s ../node/bin/npm .

npm-set-global-modules-dir

INFO "Done."
