#!/usr/bin/env bash

# Update all modules to their newest versions - including major

source bash-helpers

INFO "Checking for outdated libs..."
npm outdated

INFO "To update press enter"
read

INFO "Upgrading libs..."
npx -p npm-check-updates ncu -u

INFO "done."
