#!/usr/bin/env node

// Find and print README.md of node executable

var fs = require("fs")
var path = require("path")
var exec = require("child_process").execSync

const [, , cmd] = process.argv

var executable = exec(`bash -c "cd / && type -p '${cmd}'"`)
  .toString()
  .trim()

var executableDir = path.dirname(executable)
var linkDst = executable

try {
  linkDst = fs.readlinkSync(executable)
} catch (e) {
  // might not be a link
}

var abs = path.join(executableDir, linkDst)
var modulePath = abs.replace(/(^.+node_modules\/(@.+?\/)*.+?\/).+$/, "$1")
var readme = modulePath + "README.md"

if (!fs.existsSync(readme)) {
  process.exit(0)
}

fs.createReadStream(readme).pipe(process.stdout)
