#!/usr/bin/env bash

# Setup nvm (node version manager)

source bash-helpers

wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

cat << ''EOF > ~/.bashrc.d/nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
EOF
