#!/usr/bin/env bash

# Setup nvm (node version manager)

source bash-helpers

INFO "Make sure you don't have a fake git-cli setup."

wget --no-check-certificate -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

mkdir -p ~/.bashrc.d

cat << ''EOF > ~/.bashrc.d/nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
EOF

INFO "Now logout and in again to update your environment."
INFO "Then to install node run:"
INFO "nvm install node"
