#!/bin/bash

# Setup user dir for cpan perl libs using local::lib and cpanm

set -e

if [[ ! $REMOTE_HOME ]] ; then
    REMOTE_HOME=$HOME
fi

dst=$REMOTE_HOME/perl5
bin=$dst/bin
bashrc=$REMOTE_HOME/.bashrc

tmp=$(mktemp -d)
cd $tmp

echo
echo "Setting up local::lib..."
echo

wget -q http://cpan.metacpan.org/authors/id/H/HA/HAARG/local-lib-2.000008.tar.gz
tar xfz local-lib*tar.gz
rm *tar.gz

cd local*
perl Makefile.PL --bootstrap=$dst
make install

echo
echo "Setting up cpanm..."
echo

wget -q http://xrl.us/cpanm
chmod +x cpanm
mkdir -p $bin
mv cpanm $bin/

echo
echo "Updating bashrc..."
echo

echo 'eval "$(perl -I'$dst'/lib/perl5 -Mlocal::lib='$dst')"' > bashrc
echo 'alias cpan="(echo use cpanm >&2 ; exit 1)"' >> bashrc
echo 'alias cpanm="cpanm -nq"' >> bashrc
echo 'PATH='$bin':$PATH' >> bashrc
cat $bashrc >> bashrc
cp bashrc $bashrc

echo "done."
