#!/bin/bash

# Install perlbrew

set -e
wcat http://install.perlbrew.pl | bash > /dev/null
source ~/perl5/perlbrew/etc/bashrc
perlbrew init > /dev/null
perlbrew install-cpanm > /dev/null

INFO "You have to re-login now for changes to take effect."
