#!/usr/bin/env bash

# Emulate a pipe for a program that does not support one itself like eslint

source bash-helpers

file=$(tempfile)
original=$file.org

trap 'test -e $file && rm $file ; rm $original' ERR EXIT

tee -a $original > $file

set +e
"$@" $file &>/dev/null || error=1
set -e

if [[ $error ]]; then
    cat $original
    exit 1
fi

cat $file
