#!/usr/bin/env bash

# Setup log rotation for pm2

source bash-helpers

pm2 install pm2-logrotate
pm2 set pm2-logrotate:max_size '3M'
pm2 set pm2-logrotate:compress true
pm2 set pm2-logrotate:retain 31
pm2 set pm2-logrotate:rotateInterval: '* * */1 * *'
pm2 set pm2-logrotate:dateFormat 'DD'

# Check every 10 minutes for file size
pm2 set pm2-logrotate:workerInterval '600'

