#!/bin/bash

# Send a POST request to a website

source bash-helpers

file=${1?Specify file containing json post data}
url=${2?Specify url to post to}

curl -H "Content-Type: application/json" -X POST -d "@${file}" "$url"
