#!/usr/bin/env perl

# Run a program and pretty print all its outputs

use strict;
use warnings;
no warnings 'uninitialized';
use Cwd qw(abs_path);

use Capture::Tiny ':all';

my ( $stdout, $stderr, $exit_code ) = capture {
    system(@ARGV);
};

$exit_code = $exit_code >> 8;

chomp($stdout);
if ($stdout) {
    $stdout = "--- STDOUT " . ( "-" x 69 ) . "\n" . $stdout . "\n";
}

chomp($stderr);
if ($stderr) {
    $stderr = "--- STDERR " . ( "-" x 69 ) . "\n" . $stderr . "\n";
}

my $exit_code_message;
if ($exit_code) {
    $exit_code_message
        = "--- EXITED WITH " . ( "-" x 64 ) . "\n" . $exit_code . "\n";
}

my $output
    = "--- SHELL COMMAND "
    . ( "-" x 62 ) . "\n"
    . join( " ", @ARGV ) . "\n"
    . "--- LAUNCHED FROM "
    . ( "-" x 62 ) . "\n"
    . abs_path() . "\n"
    . $exit_code_message
    . $stdout
    . $stderr
    . ( "-" x 80 ) . "\n";

print STDOUT $output;

exit $exit_code;
