#!/usr/bin/env perl

# Run a programs tests if any exist otherwise the program itself

use strict;
use warnings;
no warnings 'uninitialized';
use Path::Tiny;

my $file     = $ARGV[0] || die "Specify file.";
my $path     = path($file)->absolute;
my $basename = $path->basename;
my $cmd;

if ( $path =~ /\.t$/ ) {
    my $wd = $path->parent->parent;
    $cmd = "cd $wd && prove -Pretty $path";
}
elsif ( $path =~ /\/bin\/$basename/ ) {

    my $wd        = $path->parent->parent;
    my $test_file = $wd->child("t")->child( $basename . ".t" );

    $cmd = "cd $wd && prove -Pretty $test_file" if $test_file->exists;
}
else {
    $cmd = $path;
}

print STDERR "Running $cmd\n";
exec $cmd;
