#!/bin/bash

# Send remote host alias to remote host to display in prompt etc

source bash-helpers
opts="$@"

remote_host=$(echo $opts | perl -ne 'print $3 if /(-\S+\s+|\S+=\S+\s+)*(\w+@)*(\S+)/i')

LC_BASHRC_REMOTE_HOST_ALIAS=$remote_host \
  alternative-run $0 "$opts"
