#!/bin/bash
# Change local sshd config to disallow password authentication and restart sshd

set -e

gotroot

cat << EOF >> /etc/ssh/sshd_config
# added by ssh-server-turn-off-password-authentication
ChallengeResponseAuthentication no
PasswordAuthentication no
UsePAM no
EOF

service ssh restart
