#!/bin/bash

# Save ssh-agent environemnt variables to be loaded in another session or on
# reconnect inside screen or tmux.

SSHVARS="SSH_CLIENT SSH_TTY SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"

for x in ${SSHVARS} ; do
    (eval echo $x=\$$x) | sed  's/=/="/
                                s/$/"/
                                s/^/export /'
done 1>$REMOTE_HOME/.ssh/agent_env
