#!/usr/bin/env bash

# Flash the terminal background

source bash-helpers

function cleanup() {
  printf \\e[?5l
}
trap cleanup ERR INT

message="$@"

if [[ $TMUX ]] ; then
  # escape sequences to change terminal background do not work in tmux.
  echo "Detaching from tmux..."
  tmux detach -E "term-flash Detached from tmux. $message"
  exit
fi

echo "$message"
while true ; do
  printf \\e[?5h
  sleep 1
  printf \\e[?5l
  sleep 1
done
