#!/usr/bin/env bash

# Flash the terminal background

source bash-helpers

function cleanup() {
  printf \\e[?5l
}
trap cleanup ERR INT

message="$@"

if [[ $TMUX ]] ; then
  exec tmux-flash "$message"
fi

echo "$message"
while true ; do
  tmux set -g window-active-style 'bg=colour9'
  # printf \\e[?5h
  sleep 1
  tmux set -g window-active-style 'bg=colour231'
  # printf \\e[?5l
  sleep 1
done
