#!/bin/bash
# Convert any file to text

source bash-helpers

file="$@"

INFO "Converting file $file"

if [[ -e txt ]] ; then
  DIE 'txt directory exists'
fi

extension=$(extension $file)
type=$(file -b --mime-type "$file")
out="txt/$file"
dir="txt/"`dirname "$file"`
mkdir -p "$dir"

DEBUG "type: $type"

if [[ "$type" =~ "text" ]] ; then
    RETURN
fi

if [[ "$type" =~ "xml" ]] ; then
    RETURN
fi

if [[ "$type" =~ "x-msaccess" ]] ; then
    for table in $(mdb-tables "$file") ; do
        INFO "Exporting database table $table..."
        mdb-export -D '%F %T' "$file" "$table" > "$out.table-$table.csv"
    done
    RETURN
fi

if [[ "$extension" = "pdf" ]] ; then
    pdftotext "$file" "$out.txt"
    RETURN
fi

if [[ "$extension" = "xlsx" ]] ; then
    xlsx2csv -s 0 "$file" "$out.csv"
    RETURN
fi

if [[ "$extension" = "docx" ]] ; then
    docx2txt "$file" "$out.txt"
    RETURN
fi

if [[ "$extension" = "doc" ]] ; then
    catdoc "$file" > "$out.txt"
    RETURN
fi

DIE "Unknown file extension: $extension for $file"

