#!/usr/bin/env perl

use strict;
use warnings;
use JSON::PP;
use Sort::Naturally;

undef $/;
my $in = <> || exit;

my $json = JSON::PP->new;
my $dec  = $json->decode($in);

print $json->pretty->sort_by(
    sub {
        ncmp($JSON::PP::a, $JSON::PP::b);
    }
)->encode($dec);
