#!/usr/bin/env perl

# Convert a humanized time spec into seconds

use strict;
use warnings;

my ($human) = $ARGV[0] || die "Specify humanized time";

my $s = 1;
my $m = $s * 60;
my $h = $m * 60;
my $d = $h * 24;
my $w = $d * 7;
my $y = $d * 365;

my ($amount, $unit) = $human =~ /^(\d+)(.)$/g;
$amount || die "Cannot find amount in $human";
$unit   || die "Cannot find unit in $human";

print $amount * eval("\$" . $unit);
