#!/bin/bash

# Reattach to a screen or tmux session

wanted_session=$1
session=$wanted_session

if [[ ! $session ]] ; then
    session=main
fi

ssh-agent-env-grab

(
    xtitle tmux@$HOSTNAME
    if tmux has-session -t $session ; then
        exec tmux -2 att -d -t $session
    fi


    if [[ ! $wanted_session ]] ; then
        if tmux has-session ; then
            exec tmux -2 att -d
        fi
    fi

    tmux-session $session
    exec tmux -2 att -d -t $session

    xtitle "Terminal"

    exit 1

) && clear

