#!/bin/sh

# Start a named tmux session with 10 tabs

set -e

session=${1?Specify session name}

tmux new-session -d -s $session -n ""

tmux new-window -n ""
tmux new-window -n ""
tmux new-window -n ""
tmux new-window -n ""
tmux new-window -n ""
tmux new-window -n ""
tmux new-window -n ""
tmux new-window -n ""
tmux new-window -n ""
tmux new-window -n ""
tmux new-window -n ""

# tmux split-window -d -v -t $session:1 'ssh workflow@qualle3'
# tmux split-window -d -v -t $session:1 'ssh workflow@qualle2'

# tmux send-keys -t $session:1.0 C-l
# tmux send-keys -t $session:1.1 C-l
# tmux send-keys -t $session:1.2 C-l

tmux select-window -t $session:1

# xtitle "$session" tmux -2 attach-session -d -t $session
