#!/usr/bin/env bash

# Setup default firewall and rules

source bash-helpers

gotroot

apt-get install ufw
ufw allow 22
ufw enable

INFO "Firewall enabled - please check activated rules."
INFO "To remove all predefined rules run 'ufw reset' and rerun this script."
INFO "Activated rules:"

ufw status
