#!/usr/bin/env bash

# disable dash to dock tooltip

# NOTE: theme hack does not seam to work for 20.04:
# SEE ALSO: https://github.com/micheleg/dash-to-dock/issues/467
# SEE ALSO: https://github.com/micheleg/dash-to-dock/issues/1108

source bash-helpers

perl -i -pe 's/(function itemShowLabel\(\)\s*\{)/$1\nreturn\n/gs' \
  ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js
