#!/bin/bash

# Add a new user to the system without hassle

source bash-helpers

user=${1?Specify user name}
shift

if [[ ! $(id $user 2> /dev/null) ]] ; then
    sudo adduser --disabled-password --quiet --gecos "" $user "$@"

    sudo mkdir -p /home/$user/.ssh/
    sudo cp ~/.ssh/authorized_keys /home/$user/.ssh/
    sudo cp ~/.bashrc /home/$user/
    sudo chown -R $user:$user /home/$user
fi

ssh $user@localhost

