#!/bin/bash

# Setup vim environment

source bash-helpers

INFO "Setting up vim config..."

VIM_DIR=$REMOTE_HOME/.config/nvim/
mkdir -p $VIM_DIR
cd $VIM_DIR

if [[ -e .git ]] ; then
  INFO "Updating existing setup..."
  git-reset-origin
  git pull
else
  INFO "Cloning git dotvim repo..."
  git clone --depth 1 https://github.com/nilsboy/dotvim.git .
fi

INFO "Starting vim to download plugins..."

exec vi
