#!/usr/bin/env bash

# Edit input fields with vim

# Make sure vim's exit code is 0 - otherwise nothing will be saved.
# Created files are kept in /tmp - see below.

# Setup:
# - Put script in you path.
# - Add custom shortcut (i.e. ctrl+e) in gnome settings and set command to:
#   bash -l -c vim-edit

source bash-helpers

tmp=$(mktemp --suffix=.vim-edit.txt)

# NOTE: use -f to include dialogs etc?
window=$(xdotool getwindowfocus)

xdotool key ctrl+a ctrl+c

xclip -o > $tmp

gnome-terminal --maximize --wait -- vi $tmp

cat $tmp | xclip -selection clip

xdotool windowactivate --sync $window
xdotool key ctrl+v

# clear (unstick) modifier key of original shortcut i.e. ctrl+e
xdotool keyup ctrl
