#!/bin/bash

# vncviewer preconfigured to use ssh.

host=$1
port=${2:-0}

export VNC_VIA_CMD="/usr/bin/ssh -C -f -L %L:%H:%R %G sleep 20"

$(type -pf vncviewer) -encoding tight \
    -compresslevel 9 -quality 5 -x11cursor -via $host localhost:$port
